/*
    Single LUT based multipliers SA engine
*/
module sa_engine_lut#(
    parameter W_DATA = 8,
    parameter COL = 8,
    parameter ROW = 9,
    parameter W_PSUM = 19,
    parameter N_SA = 4,
    parameter N_BRAM_BYTES = 32,
    parameter PSUM_FF_DEPTH = 1024,
    parameter WEIGHT_FF_DEPTH = 512,
    parameter IMG_FF_DEPTH = 512
)(
    input i_clk,
	input s_clk,
    input psum_full,
	input i_rstn,
    input i_trigger_1,      //trigger from flattening controller, to load weights into PE blocks
    input i_done,           //indicates iteration done flag
    input i_layer_done,     //indicates layer done flag
    input [(COL * W_DATA)-1 : 0] i_weight_fifo_array_data,
    input [COL-1 : 0] i_weight_fifo_array_dv,
    input [COL-1 : 0] i_weight_fifo_array_empty,
    input [((WEIGHT_FF_ADDR + 1) * COL)-1 : 0] i_weight_fifo_array_occ,
    input [(ROW * W_DATA)-1 : 0] i_image_fifo_array_data,
    input [ROW-1 : 0] i_image_fifo_array_wren,
    input i_psum_ff_array_read_en,
    output [(W_PSUM * COL)-1 : 0] o_psum_ff_array_partial_sums,
    output o_psum_ff_array_empty,
    output o_psum_ff_array_almost_empty,
    output o_psum_ff_array_dv,
    output o_weight_fifo_array_rden,
    output [((PSUM_FF_ADDR +1))-1 :0 ] p_occupants,
    output [ROW-1 : 0]o_image_ff_array_almost_empty,
    output [ROW-1 : 0]o_image_ff_array_almost_full,
	output o_mux_sel        //generated by weight array read enable controller, should go into fifo sharing module
);

localparam IMG_FF_ADDR = $clog2(IMG_FF_DEPTH);
localparam WEIGHT_FF_ADDR = $clog2(WEIGHT_FF_DEPTH);
localparam PSUM_FF_ADDR = $clog2(PSUM_FF_DEPTH);

wire [(COL * (W_DATA + 1))-1 : 0] weights_append_dv_cdc;

//Appends data valid with weights before sending it into PE blocks
append_dv#(
    .N_DIMENSION(COL),
    .W_DATA(W_DATA)
)weight_fifo_array_dv(
    .i_data(i_weight_fifo_array_data),
    .i_data_valid(i_weight_fifo_array_dv),
    .o_data(weights_append_dv_cdc)
);

wire enb_weight_rden_ctrl_image_rden_ctrl;

//Control read enable signal of uart_rx_weight_fifo
weight_fifo_array_rden#(
    .COL(COL),
    .W_ADDR(WEIGHT_FF_ADDR),
    .ROW(ROW),
    .N_SA(N_SA),
    .N_BRAM_BYTES(N_BRAM_BYTES)
)weight_fifo_array_rden_ctrl(
    .i_clk(i_clk),
    .i_rstn(i_rstn),
    .i_start(i_trigger_1),
    .i_done(i_done),
    .i_layer_done(i_layer_done),
    .i_fifo_empty(i_weight_fifo_array_empty),
    .i_fifo_occupants(i_weight_fifo_array_occ),
    .o_fifo_read_enable(o_weight_fifo_array_rden),
    .o_sel(o_mux_sel),
    .o_enable_image_rden_ctrl(enb_weight_rden_ctrl_image_rden_ctrl)
);


wire read_rden_ctrl_image_ff_array;
wire [ROW-1 : 0] empty_image_ff_array_rden_ctrl;
wire[(ROW * W_DATA)-1 : 0] data_image_ff_array_append_dv;
wire [ROW-1:0] dv_image_ff_array_append_dv;

/*
    Delay the rden signal to FIFOs instead of using delay registers
    between PE grid and FIFOs. This reduces the number of registers
    utilized in the design.
*/

wire [ROW-1 : 0] read_rden_ctrl_image_ff_array_delayed;

rden_delay_reg#(
    .ROW(ROW)
) rden_delay_reg_image_ff_array (
    .i_clk(i_clk),
    .i_rden(read_rden_ctrl_image_ff_array),
    .o_rden_img_fifo(read_rden_ctrl_image_ff_array_delayed)
);

image_fifo_array#(
    .DIMENSION(ROW),
    .W_DATA(W_DATA),
    .W_ADDR(IMG_FF_ADDR),
    .RAM_DEPTH(IMG_FF_DEPTH)
) sa_engine_image_fifo_array (
    .i_clk(i_clk),
    .i_rstn(i_rstn),
    .i_data(i_image_fifo_array_data),
    .i_write_enable(i_image_fifo_array_wren),
    .i_read_enable(read_rden_ctrl_image_ff_array_delayed),
    .o_data(data_image_ff_array_append_dv),
    .o_fifo_empty(empty_image_ff_array_rden_ctrl),
    .o_fifo_almost_empty(o_image_ff_array_almost_empty),
    .o_fifo_almost_full(o_image_ff_array_almost_full),
    .o_fifo_full(),
    .o_fifo_dv(dv_image_ff_array_append_dv),
    .o_occupants()
);

//Appends data valid signal with image before sending it to delay registers
append_dv#(
    .N_DIMENSION(ROW),
    .W_DATA(W_DATA)
) image_fifo_array_dv (
    .i_data(data_image_ff_array_append_dv),
    .i_data_valid(dv_image_ff_array_append_dv),
    .o_data(image_append_dv_cdc)
);

wire [((W_DATA + 1) * ROW)-1 : 0] image_append_dv_cdc;

//Control read enable signal of uart_rx_image_fifo
image_fifo_array_rden#(
    .ROW(ROW),
    .W_ADDR(IMG_FF_ADDR),
    .W_DATA(W_DATA)
) image_fifo_array_rden_ctrl (
    .i_clk(i_clk),
    .i_rstn(i_rstn),
	.psum_full(psum_full),
	.i_trigger(enb_weight_rden_ctrl_image_rden_ctrl),
    .i_fifo_empty(empty_image_ff_array_rden_ctrl),
    .o_read_enable(read_rden_ctrl_image_ff_array)
);

//synchronizers for CDC, receives weights and image from weight & image fifo array respectively
(* async_reg = "true" *) reg [(COL * (W_DATA + 1))-1 : 0] weight_reg = 0;
(* async_reg = "true" *) reg [(COL * (W_DATA + 1))-1 : 0] weights_cdc_sa = 0;
(* async_reg = "true" *) reg [(ROW * (W_DATA + 1))-1 : 0] image_reg = 0;
(* async_reg = "true" *) reg [(ROW * (W_DATA + 1))-1 : 0] image_cdc_sa = 0;
always @(posedge s_clk)
begin 
    weight_reg <= weights_append_dv_cdc;
    weights_cdc_sa <= weight_reg;
    
    image_reg <= image_append_dv_cdc;
    image_cdc_sa <= image_reg;
end

/*
wire [(ROW * (W_DATA + 1)) - 1 : 0] image_delay_reg_lut_pe;

//Provides delay to image before loading it into PE grid
delay_reg #(
    .ROW(ROW),
    .W_DATA(W_DATA)
) sa_image_delay_registers (
    .in_clk(s_clk),
    .i_rstn(i_rstn),
    .in_west(image_cdc_sa),
    .pe_grid_image(image_delay_reg_lut_pe)
);
*/

wire  [((W_PSUM + 1) * COL)-1 : 0] partial_sums_sa_cdc;
//PE grid using LUT blocks as multipliers
lut_pe_grid#(
    .COL(COL),
    .ROW(ROW),
    .W_DATA(W_DATA),
    .W_PSUM(W_PSUM)
) lut_sa_block (
    .i_clk(s_clk),
    .i_rstn(i_rstn),
    .i_weight(weights_cdc_sa),
    .in_data(image_cdc_sa),
    .o_partial_sum(partial_sums_sa_cdc),
    .o_data() 
);

//synchronizers for CDC, receive partial sums from PE grid
(* async_reg = "true" *) reg [(COL * (W_PSUM + 1))-1 : 0] psum_reg = 0;
(* async_reg = "true" *) reg [(COL * (W_PSUM + 1))-1 : 0] partial_sums_cdc_seperate_dv = 0;

always@(posedge i_clk)
begin 
    psum_reg <= partial_sums_sa_cdc;
    partial_sums_cdc_seperate_dv <= psum_reg;
end

wire [(COL * W_PSUM)-1 : 0] psum_seperate_dv_psum_ff_array;
wire [COL-1 : 0] dv_seperate_dv_psum_ff_array;

//Seperated data valid signal from partial sums output coming out of each column of PE grid
seperate_psum_dv#(
    .COL(COL),
    .W_PSUM(W_PSUM)
) partial_sum_dv (
    .in_data(partial_sums_cdc_seperate_dv),
    .out_data(psum_seperate_dv_psum_ff_array),
    .out_data_valid(dv_seperate_dv_psum_ff_array)
);

/*
    Each fifo in this array stores its corrosponding column's partial sums after
    receiving it from PE blocks 
*/
fifo_array#(
    .DIMENSION(1),
    .W_DATA(W_PSUM*COL),
    .W_ADDR(PSUM_FF_ADDR),
    .RAM_DEPTH(PSUM_FF_DEPTH)
) partial_sum_fifo_array (
    .i_clk(i_clk),
    .i_rstn(i_rstn),
    .i_data(psum_seperate_dv_psum_ff_array),
    .i_write_enable(&(dv_seperate_dv_psum_ff_array)),
    .i_read_enable(i_psum_ff_array_read_en),
    .o_data(o_psum_ff_array_partial_sums),
    .o_fifo_empty(o_psum_ff_array_empty),
    .o_fifo_almost_empty(o_psum_ff_array_almost_empty),
    .o_data_valid(o_psum_ff_array_dv),
    .o_fifo_full(),
    .o_occupants(p_occupants)
);

endmodule
