/*
    Systolic array block along with the registers to provide delay 
    while sending data into rows of systolic array
*/
module systolic_array #(
    parameter ROW = 9, 
    parameter COL = 3, 
    parameter TOTAL_BYTES = ROW * COL,
    parameter W_DATA = 8
)(  input in_clk, 
    input in_sel,   
    input [(COL * W_DATA) - 1:0] in_north,  //8 bit weights 
    input [(ROW * (W_DATA + 1)) - 1:0] in_west,    //8 bit data 
    output [(ROW * (W_DATA + 1)) - 1:0] out_east,  //32 bit output from last row
    output [(COL * 32) - 1:0] out_south,    //8 bit data output from the last column
    output last_row_i_data_valid    //shows the validity of input 8 bit data which is going into the last row of systolic array
);

wire [(ROW * (W_DATA + 1)) - 1 : 0] data_to_be_passed;  //9 bits data output from registers (used for providing delay) going into rows of systolic array 

assign last_row_i_data_valid = data_to_be_passed[8];

sa#(
    .N_COLS(COL),
    .N_ROWS(ROW),
    .W_DATA(W_DATA)
) sa_grid (
    .i_clk(in_clk),
    .i_sel(in_sel),
    .i_weights(in_north),
    .i_data(data_to_be_passed),
    .o_partial_sums(out_south),
    .o_data(out_east)
);

//registers for providing row wise delay to the input data
reg_module #(
    .ROW (ROW)
  //  .W_DATA(W_DATA)
) delay_reg (
    .in_clk (in_clk), 
    .in_west (in_west) ,
    .data_to_be_passed (data_to_be_passed)
);

endmodule

/* Multiple registers are generated by this module for each row to provide delay 
to the inputs coming into rows of the systolic array */
/*
module reg_module #(
    parameter ROW = 9,
    parameter W_DATA = 8
)(  input in_clk, 
    input [(ROW * (W_DATA + 1)) - 1 : 0] in_west,
    output [(ROW * (W_DATA + 1)) - 1 : 0] data_to_be_passed
);

//8 bit input data being fetched from registers goes as input into the first column of systolic array
assign data_to_be_passed [80:72] = in_west[80:72];  

genvar i , j;
    generate
    for (i = 0; i < ROW; i = i + 1) begin: FOR_ROW
        for (j = 0; j < i; j = j + 1) begin: FC_IN
        wire [8:0] data_out_reg;
            if (j == 0 && j == i - 1) begin
                data_reg #(.W_DATA(W_DATA))
                dr (.clk(in_clk),
                    .o_data(data_to_be_passed[((ROW - i) * (W_DATA + 1) )- 1 -: (W_DATA + 1)]),
                    .i_data(in_west[((ROW - i) * (W_DATA + 1)) - 1 -: (W_DATA + 1)])
                );
            end else if (j == 0) begin
                data_reg#(.W_DATA(W_DATA)) 
                dr (.clk(in_clk),
                    .o_data(data_out_reg),
                    .i_data(in_west[((ROW - i) * (W_DATA + 1)) - 1 -: (W_DATA + 1)])
                );
            end else if (j == i - 1) begin
                data_reg#(.W_DATA(W_DATA)) 
                dr (.clk(in_clk),
                    .o_data(data_to_be_passed[((ROW - i) * (W_DATA + 1)) - 1 -: (W_DATA + 1)]),
                    .i_data(FOR_ROW[i].FC_IN[j-1].data_out_reg)
                );
            end else begin
                data_reg #(.W_DATA(W_DATA))
                dr (.clk(in_clk),
                    .o_data(data_out_reg),
                    .i_data(FOR_ROW[i].FC_IN[j-1].data_out_reg)
                );
            end
        end
    end
endgenerate

endmodule    

//Delay is provided to the inputs of rows in systolic array by storing it into this register
module data_reg#(
    parameter W_DATA = 8
)(
    input clk, 
    input [W_DATA-1 : 0] i_data, 
    output reg [W_DATA-1 : 0] o_data= 0
); 
always @(posedge clk) begin 
    o_data <= i_data; 
end 

endmodule*/

module reg_module #(
    parameter ROW = 9
)(  input in_clk, 
    input [(ROW * 9) - 1 : 0] in_west,
    output [(ROW * 9) - 1 : 0] data_to_be_passed
);

assign data_to_be_passed [80:72] = in_west[80:72];

genvar i , j;
    generate
    for (i = 0; i < ROW; i = i + 1) begin: FOR_ROW
        for (j = 0; j < i; j = j + 1) begin: FC_IN
        wire [8:0] data_out_reg;
            if (j == 0 && j == i - 1) begin
                data_reg dr (
                    .clk(in_clk),
                    .o_data(data_to_be_passed[(ROW - i) * 9 - 1 -: 9]),
                    .i_data(in_west[(ROW - i) * 9 - 1 -: 9])
                );
            end else if (j == 0) begin
                data_reg dr (
                    .clk(in_clk),
                    .o_data(data_out_reg),
                    .i_data(in_west[(ROW - i) * 9 - 1 -: 9])
                );
            end else if (j == i - 1) begin
                data_reg dr (
                    .clk(in_clk),
                    .o_data(data_to_be_passed[(ROW - i) * 9 - 1 -: 9]),
                    .i_data(FOR_ROW[i].FC_IN[j-1].data_out_reg)
                );
            end else begin
                data_reg dr (
                    .clk(in_clk),
                    .o_data(data_out_reg),
                    .i_data(FOR_ROW[i].FC_IN[j-1].data_out_reg)
                );
            end
        end
    end
endgenerate

endmodule    

//Delay is provided to the inputs of rows in systolic array by storing it into this register
module data_reg(
    input clk, 
    input [8:0] i_data, 
    output reg [8:0] o_data= 0
); 
always @(posedge clk) begin 
    o_data <= i_data; 
end 

endmodule