/*                            mux module 
- The output from the previous adder trees is initially stored in the DRAM and 
subsequently fetched into a set of 32 FIFOs (First-In-First-Out buffers).

- If N is the no. of SA engines running parallelly,on each positive edge of the 
clock signal, data is read from the first N FIFOs. Then, on the subsequent 
positive edge, data is read from the next N FIFOs, and so forth, until all 32 
FIFOs have been read.

- To facilitate the distribution of data from the FIFOs to the SA engines, 
8 multiplexers operate in parallel. Each multiplexer is responsible for 
selecting data from a specific set of FIFOs. Specifically, the multiplexers are 
configured to receive data from the following FIFO positions: x, x+N, x+2N, and 
x+3N.

- And so fifo_data1, fifo_data2, fifo_data3 and fifo_data4 are the inputs and based
on the mux_sel generated by the fifo_controller of the design data_o_fifo is 
selected and given to one of the inputs of the adder.

- The module has been replicated N times, corresponding to the number of 
Systolic Array (SA) engines. This allows for the creation of 8 instances of the 
output block, each capable of running independently and simultaneously.

*/
module mux #(
    parameter                   DATA_WIDTH = 20,
    parameter                   MUX_SEL_WIDTH = 2


)(
    input [DATA_WIDTH-1:0]      fifo_data1,
    input [DATA_WIDTH-1:0]      fifo_data2,
    input [DATA_WIDTH-1:0]      fifo_data3,
    input [DATA_WIDTH-1:0]      fifo_data4,
    input [MUX_SEL_WIDTH-1:0]   mux_sel,
    output [DATA_WIDTH-1:0]     data_o_fifo
);

// If the select signal of the mux is 00 --> then select fifo1 data,
//                             mux is 01 --> then select fifo9 data,
//                             mux is 10 --> then select fifo17 data,
//                             mux is 11 --> then select fifo25 data,

assign data_o_fifo = (mux_sel == 2'b00) ? fifo_data1 : 
                     (mux_sel == 2'b01) ? fifo_data2 : 
                     (mux_sel == 2'b10) ? fifo_data3 : 
                     (mux_sel == 2'b11) ? fifo_data4 : 0;


endmodule



module mux_gen #(
    parameter DATA_WIDTH = 8,
    parameter MUX_SEL_WIDTH = 2,
    parameter N = 8

)(
    input [DATA_WIDTH*N-1:0]      gen_fifo_data1,
    input [DATA_WIDTH*N-1:0]      gen_fifo_data2,
    input [DATA_WIDTH*N-1:0]      gen_fifo_data3,
    input [DATA_WIDTH*N-1:0]      gen_fifo_data4,
    input [MUX_SEL_WIDTH*N-1:0]   gen_mux_sel,
    output [DATA_WIDTH*N-1:0]     gen_data_o_fifo
);


genvar i;
generate 
    for (i = 0 ; i < N ; i = i + 1) begin : MUX_INSTANCES
        mux #(
            .DATA_WIDTH(DATA_WIDTH),
            .MUX_SEL_WIDTH(MUX_SEL_WIDTH)
        )
        mux_gen(
            .fifo_data1(gen_fifo_data1[DATA_WIDTH*i+:DATA_WIDTH]),
            .fifo_data2(gen_fifo_data2[DATA_WIDTH*i+:DATA_WIDTH]),
            .fifo_data3(gen_fifo_data3[DATA_WIDTH*i+:DATA_WIDTH]),
            .fifo_data4(gen_fifo_data4[DATA_WIDTH*i+:DATA_WIDTH]),
            .mux_sel(gen_mux_sel[MUX_SEL_WIDTH*i+:MUX_SEL_WIDTH]),
            .data_o_fifo(gen_data_o_fifo[DATA_WIDTH*i+:DATA_WIDTH])
        );
end
endgenerate 
endmodule