#!/bin/env python
from os import write
from serial import Serial
from random import randint
import sys
import threading
import numpy as np

def print_usage(name):
    print(name + " <PORT> <BAUDRATE>")

if len(sys.argv) < 3:
    print("Not enough arguments provided!")
    print_usage(sys.argv[0])
    exit()

port = sys.argv[1]
baudrate = int(sys.argv[2])

# Open the serial port
ser = Serial(port, baudrate)

np.random.seed(24)
n_rows = 20
n_cols = 9
w_rows = 9
w_cols = 4

# List to store matrix_A objects
matrix_A_list = []

def compute(input, idim, weights, wdim):
    input = np.array(input).reshape(idim)
    weights = np.array(weights).reshape(wdim).T
    with open("out_data.txt", "a") as f:
        for i in range(weights.shape[0]):
            for j in range(input.shape[0]):
                f.write(str(np.dot(weights[i], input[j])) + " ")
            f.write("\n")
        f.write("\nEnd of output for one engine \n")
        f.write("\n")


def transform(w):
    new_mat=[]
    for i in range((n_cols - 1),-1,-1):
        new_mat.append(w[i])
    return np.array(new_mat)

def write_thread():
    while True:
        c_count = 1
        while c_count:
            input("[Enter] to weight matrix\n")
            matrix_A = np.random.randint(-128, 127, size=(w_rows, w_cols), dtype=np.int8)
            matrix_sA = matrix_A.astype(np.int32)
            matrix_A_list.append(matrix_sA)
            for row in matrix_A:
                print(row)
                ser.write(row.tobytes())
            c_count -= 1

        r_count = 2
        while r_count:
            input("\n[Enter] to send image matrix\n")
            matrix_B = np.random.randint(-128, 127, size=(n_rows, n_cols), dtype=np.int8)
            for matrix_sA in matrix_A_list:
                transformed_A = transform(matrix_sA)
                compute(matrix_B, (n_rows, n_cols), transformed_A, (w_rows, w_cols))
            for row in matrix_B:
                print(row)
                ser.write(row.tobytes())
            r_count -= 1

write_thread()

ser.close()
