`include "../common/instructions.vh"
`include "../common/arch_param.vh"

module top_master_slave_integrate #(parameter OP_CODE_WIDTH = 4, 
    parameter CNT = (INPUT_WIDTH/OUTPUT_WIDTH),
    parameter INPUT_WIDTH = 256,
    parameter OUTPUT_WIDTH = 8,
    parameter NO_OF_OPERATOR = 6,
    parameter ADDRESS_WIDTH = 32,
    parameter IW_WIDTH = 10,
    parameter IH_WIDTH = 10,
    parameter OW_WIDTH = 10,
    parameter OH_WIDTH = 10,
    parameter IC_WIDTH = 10,
    parameter KN_WIDTH = 10,
    parameter KW_WIDTH = 4,
    parameter KH_WIDTH = 4,
    parameter KC_WIDTH = 10,
    parameter CONV_TYPE_WIDTH = 2,
    parameter STRIDE_WIDTH = 4,
    parameter PAD_LEFT_WIDTH = 3,
    parameter PAD_RIGHT_WIDTH = 3,
    parameter PAD_TOP_WIDTH = 3,
    parameter PAD_BOTTOM_WIDTH = 3,
    parameter CONV_Im2colPrefetch_WIDTH = 1,
    parameter CONV_CHANNELDUPLICATE_WIDTH = 1,
    parameter WEIGHTROWS_WIDTH = 16,
    parameter WEIGHTCOLS_WIDTH = 16,
    parameter INPUTROWS_WIDTH = 16,
    parameter DROPOUTCONSTANT_WIDTH = 8,
    parameter FLATTEN_WIDTH = 1,
    parameter IMAGEDIN_WIDTH = 20,
    parameter FC_VEC2MATCOL_WIDTH = 16,
    parameter CHANNELITR_WIDTH = 12,
    parameter KERNELITR_WIDTH = 12,
    parameter IMAGEDIMOUTPUT_WIDTH = 16,
    parameter IMAGEDIMACC_WIDTH = 16,
    parameter ACCEN_WIDTH = 1,
    parameter BNEN_WIDTH = 1,
    parameter ACTEN_WIDTH = 1,
    parameter DISPATCH_ID_WIDTH = 32,
    parameter DISPATCHEN_WIDTH = 1,
    parameter ACC_ONCHIP_WIDTH = 1,
    parameter ACTTYPE_WIDTH = 4,
    parameter ACTPARAM_WIDTH = 8,
    parameter LR_NEG_ALPHA_WIDTH = 10,
    parameter LR_POS_ALPHA_WIDTH = 10,
    parameter QUANTEN_WIDTH = 1,
    parameter QUANTSCALE_WIDTH = 16,
    parameter QUANTSHIFT_WIDTH = 5,
    parameter POOLEN_WIDTH = 1,
    parameter GBL_POOL_SCALE_WIDTH = 4,
    parameter GBL_POOL_SHIFT_WIDTH = 4,
    parameter GBL_POOL_EN_WIDTH = 1,
    parameter BIASEN_WIDTH = 1,
    parameter BNCHANNELS_WIDTH = 10,
    parameter BiasWidth_WIDTH = 8,
    
    `ifdef MEGA_POOL 
    parameter POOL_IW_WIDTH = 10,
    parameter POOL_IH_WIDTH = 10,
    parameter POOL_IC_WIDTH = 10,
    parameter POOL_IMG_STA_ADD_WIDTH = 10,
    parameter POOL_IMG_END_ADD_WIDTH = 10,
    parameter POOLTYPE_WIDTH = 3,
    parameter POOLSCALE_WIDTH = 8,
    parameter POOLSHIFT_WIDTH = 4,
    parameter POOLWIDTH_WIDTH = 4,
    parameter POOLHEIGHT_WIDTH = 4,
    parameter POOLSTRIDE_W_WIDTH = 4,
    parameter POOLSTRIDE_H_WIDTH = 4,
    parameter POOLCEIL_WIDTH = 1,
    parameter POOLPAD_L_WIDTH = 4,
    parameter POOLPAD_R_WIDTH = 4,
    parameter POOLPAD_T_WIDTH = 4,
    parameter POOLPAD_B_WIDTH = 4,
    parameter POOL_PREFETCH_WIDTH = 1,
    `elsif POOL
    parameter POOLTYPE_WIDTH = 1,
    parameter POOLWIDTH_WIDTH = 4,
    parameter POOLHEIGHT_WIDTH = 4,
    parameter POOLSTRIDE_WIDTH = 4,
    parameter POOLPAD_WIDTH = 4,
    parameter POOLCEIL_WIDTH = 4,
    parameter POOLMODCOUNT_WIDTH = 4,
    parameter POOLPADSIDES_WIDTH = 4,
    parameter POOLSCALE_WIDTH = 4,
    parameter POOLSHIFT_WIDTH = 4,
    `endif

    parameter ELTWISE_TYPE_WIDTH = 4,
    parameter ELTWISE_SCALE_WIDTH = 32,
    parameter ELTWISE_ZEROPOINT_WIDTH = 8,
    parameter RESIZE_IW_WIDTH = 10,
    parameter RESIZE_IH_WIDTH = 10,
    parameter RESIZE_IC_WIDTH = 10,
    parameter RESIZE_IMG_STA_ADD_WIDTH = 10, 
    parameter RESIZE_IMG_END_ADD_WIDTH = 10,
    parameter CONV_StartRowSkip_WIDTH = 4,
    parameter CONV_EndRowSkip_WIDTH = 4,
    parameter TRANSPOSE_IC_WIDTH = 12,
    parameter TRANSPOSE_IH_WIDTH = 12,
    parameter TRANSPOSE_IW_WIDTH = 12,
    parameter OutputBlock_FlatController_WIDTH = 1,
    parameter OutputBlock_AccumulantReadFirst_WIDTH = 1,
    parameter OutputBlock_OpWidth_WIDTH = 3,
    // Concat operator 
    parameter CONCAT_Image1StartAddress_WIDTH = 32,
    parameter CONCAT_Image2StartAddress_WIDTH = 32,
    parameter CONCAT_Image3StartAddress_WIDTH = 32,
    parameter CONCAT_Image4StartAddress_WIDTH = 32,
    parameter CONCAT_IH1_WIDTH = 10,
    parameter CONCAT_IH2_WIDTH = 10,
    parameter CONCAT_IH3_WIDTH = 10,
    parameter CONCAT_IH4_WIDTH = 10,
    parameter CONCAT_KN1_WIDTH = 10,
    parameter CONCAT_KN2_WIDTH = 10,
    parameter CONCAT_KN3_WIDTH = 10,
    parameter CONCAT_KN4_WIDTH = 10,
    parameter CONCAT_InNum_WIDTH = 3
  
)      
    (
    input [(INPUT_WIDTH)-1 : 0] din,
    input start,
    input clk,
    input [(OP_CODE_WIDTH)-1 : 0] opcode,
    output [(NO_OF_OPERATOR)-1 : 0] valid, // change this one too
    output [OP_CODE_WIDTH - 1 : 0] opcode_conv,
    output [IW_WIDTH - 1 : 0] IW,
    output [IH_WIDTH - 1 : 0] IH,
    output [IC_WIDTH - 1 : 0] IC,
    output [KN_WIDTH - 1 : 0] KN,
    output [KW_WIDTH - 1 : 0] KW,
    output [KH_WIDTH - 1 : 0] KH,
    output [KC_WIDTH - 1 : 0] KC,
    output [CONV_TYPE_WIDTH - 1 : 0] conv_type,
    output [STRIDE_WIDTH - 1 : 0] Stride,
    output [PAD_LEFT_WIDTH - 1 : 0] Pad_left,
    output [PAD_RIGHT_WIDTH - 1 : 0] Pad_right,
    output [PAD_TOP_WIDTH - 1 : 0] Pad_top,
    output [PAD_BOTTOM_WIDTH - 1 : 0] Pad_bottom,
    output [CONV_StartRowSkip_WIDTH-1:0] start_row_skip,
    output [CONV_EndRowSkip_WIDTH-1:0] end_row_skip ,
    output [CONV_Im2colPrefetch_WIDTH - 1 : 0] CONV_Im2colPrefetch,
    output [CONV_CHANNELDUPLICATE_WIDTH - 1 : 0] CONV_ChannelDuplicate,
    output [ADDRESS_WIDTH - 1 : 0] ImageStartAddress_conv,
    output [ADDRESS_WIDTH - 1 : 0] ImageEndAddress_conv,
    output [ADDRESS_WIDTH - 1 : 0] WeightStartAddress_conv,
    output [ADDRESS_WIDTH - 1 : 0] WeightEndAddress_conv,

    `ifdef FC
    output [OP_CODE_WIDTH - 1 : 0] opcode_FC,
    output [WEIGHTROWS_WIDTH - 1 : 0] weightrows,
    output [WEIGHTCOLS_WIDTH - 1 : 0] weightcols,
    output [INPUTROWS_WIDTH - 1 : 0] inputrows,
    output [DROPOUTCONSTANT_WIDTH -1 : 0] dropoutconstant,
    output [FLATTEN_WIDTH -1 : 0] flatten,
    output [IMAGEDIN_WIDTH -1 : 0] imagedim_FC,
    output [ADDRESS_WIDTH - 1 : 0] ImageStartAddress_FC,
    output [ADDRESS_WIDTH - 1 : 0] ImageEndAddr_FC,
    output [ADDRESS_WIDTH - 1 : 0] WeightStartAddress_FC,
    output [ADDRESS_WIDTH - 1 : 0] WeightEndAddress_FC,
    output [FC_VEC2MATCOL_WIDTH -1 : 0] FC_Vec2MatCols,
    `endif //FC
    
    output [OP_CODE_WIDTH -1 : 0] opcode_OB,
    output [ADDRESS_WIDTH - 1 : 0] accumulantaddr,
    output [ADDRESS_WIDTH - 1 : 0] outputaddr,
    output [CHANNELITR_WIDTH -1 : 0] channelItr,
    output [KERNELITR_WIDTH - 1 : 0] kernelItr,
    output [IMAGEDIMOUTPUT_WIDTH -1 : 0] ImageDimOutput,
    output [IMAGEDIMACC_WIDTH -1 : 0] ImageDimAcc,
    output [ACCEN_WIDTH -1 : 0] AccEn,
    output [DISPATCH_ID_WIDTH-1 : 0] DispatchId,
    output [DISPATCHEN_WIDTH-1 : 0] DispatchEn,
    output [ACC_ONCHIP_WIDTH-1 : 0] Acc_onchip,
    output [OH_WIDTH - 1 : 0] OB_OH,
    output [OW_WIDTH - 1 : 0] OB_OW,
    output [OP_CODE_WIDTH - 1 : 0] opcode_TB,
    output [BNEN_WIDTH - 1 : 0] BNEn,
    output [ACTEN_WIDTH - 1 : 0] ActEn,
    output [ACTTYPE_WIDTH - 1 : 0] acttype,
    output [ACTPARAM_WIDTH - 1 : 0] ActParam,
    output [LR_NEG_ALPHA_WIDTH - 1 : 0] LR_NegAlpha,
    output [LR_POS_ALPHA_WIDTH - 1 : 0] LR_PosAlpha,
    output [QUANTEN_WIDTH - 1 : 0] QuantEn,
    output [QUANTSCALE_WIDTH - 1 : 0] quantscale,
    output [QUANTSHIFT_WIDTH - 1 : 0] quantshift,

    `ifdef GLOBAL_POOL 
    output [GBL_POOL_SCALE_WIDTH - 1 : 0] gbl_pool_scale,
    output [GBL_POOL_SHIFT_WIDTH - 1 : 0] gbl_pool_shift,
    output [GBL_POOL_EN_WIDTH - 1 : 0] gbl_pool_en,
    `endif

    output [POOLEN_WIDTH - 1 : 0] PoolEn,
    output [BIASEN_WIDTH - 1 : 0] BiasEn,
    output [BiasWidth_WIDTH - 1 : 0] BiasWidth,
    output [ADDRESS_WIDTH - 1 : 0] BiasStartAddress,
    output [ADDRESS_WIDTH - 1 : 0] BiasEndAddress,
    
    `ifdef MEGA_POOL
    output [OP_CODE_WIDTH -1 : 0] opcode_pool,
    output [POOL_IW_WIDTH - 1 : 0] pool_iw,
    output [POOL_IH_WIDTH - 1 : 0] pool_ih,
    output [POOL_IC_WIDTH - 1 : 0] pool_ic,
    output [POOL_IMG_STA_ADD_WIDTH - 1 : 0] pool_img_sta_add,
    output [POOL_IMG_END_ADD_WIDTH - 1 : 0] pool_img_end_add,
    output [POOLTYPE_WIDTH - 1 : 0] pooltype,
    output [POOLSCALE_WIDTH - 1 : 0] poolscale,
    output [POOLSHIFT_WIDTH - 1 : 0] poolshift,
    output [POOLWIDTH_WIDTH - 1 : 0] poolwidth,
    output [POOLHEIGHT_WIDTH - 1 : 0] poolheight,
    output [POOLSTRIDE_W_WIDTH - 1 : 0] poolstride_w,
    output [POOLSTRIDE_H_WIDTH - 1 : 0] poolstride_h,
    output [POOLCEIL_WIDTH - 1 : 0] poolceil,
    output [POOLPAD_L_WIDTH - 1 : 0] pool_pad_l,
    output [POOLPAD_R_WIDTH - 1 : 0] pool_pad_r,
    output [POOLPAD_T_WIDTH - 1 : 0] pool_pad_t,
    output [POOLPAD_B_WIDTH - 1 : 0] pool_pad_b,
    output [POOL_PREFETCH_WIDTH - 1:0] pool_prefetch,
    `elsif POOL
    output [POOLTYPE_WIDTH - 1 : 0] pooltype,
    output [POOLWIDTH_WIDTH - 1 : 0] poolwidth,
    output [POOLHEIGHT_WIDTH - 1 : 0] poolheight,
    output [POOLSTRIDE_WIDTH - 1 : 0] poolstride,
    output [POOLPAD_WIDTH - 1 : 0] poolpadding,
    output [POOLCEIL_WIDTH - 1 : 0] poolceil,
    output [POOLMODCOUNT_WIDTH - 1 : 0] poolModCount,
    output [POOLPADSIDES_WIDTH - 1 : 0] poolpadsides,
    output [POOLSCALE_WIDTH - 1 : 0] poolscale,
    output [POOLSHIFT_WIDTH - 1 : 0] poolshift,
    `endif

    output [OP_CODE_WIDTH - 1 : 0] opcode_EltWise,
    output [ELTWISE_TYPE_WIDTH - 1 : 0] EltWise_type,
    output [ELTWISE_SCALE_WIDTH - 1 : 0] LeftOperand_Scale,
    output [ELTWISE_SCALE_WIDTH - 1 : 0] RightOperand_Scale,
    output [ELTWISE_ZEROPOINT_WIDTH - 1 : 0] LeftOperand_zero_point,
    output [ELTWISE_ZEROPOINT_WIDTH - 1 : 0] RightOperand_zero_point,
    output [IW_WIDTH - 1 : 0] EltWise_IW,
    output [IH_WIDTH - 1 : 0] EltWise_IH,
    output [IC_WIDTH - 1 : 0] EltWise_IC,   
    output [ADDRESS_WIDTH - 1 : 0] LeftOperand_StartAddress,
    output [ADDRESS_WIDTH - 1 : 0] RightOperand_StartAddress,
    output [ADDRESS_WIDTH - 1 : 0] LeftOperand_EndAddress,
    output [ADDRESS_WIDTH - 1 : 0] RightOperand_EndAddress,
    output [OP_CODE_WIDTH -1 : 0] opcode_resize,
    output [RESIZE_IW_WIDTH - 1 : 0] resize_iw,
    output [RESIZE_IH_WIDTH - 1 : 0] resize_ih,
    output [RESIZE_IC_WIDTH - 1 : 0] resize_ic,
    output [RESIZE_IMG_STA_ADD_WIDTH - 1 : 0] resize_img_sta_add,
    output [RESIZE_IMG_END_ADD_WIDTH - 1 : 0] resize_img_end_add,
    output [OutputBlock_AccumulantReadFirst_WIDTH-1:0]OutputBlock_AccumulantReadFirst,
    output [OutputBlock_OpWidth_WIDTH-1:0] OB_OpWidth,

    `ifdef TRANSPOSE
    output [OP_CODE_WIDTH-1:0] rt_opcode,
    output [ADDRESS_WIDTH-1:0] ReshapeTranspose_start_address,
    output [TRANSPOSE_IH_WIDTH-1:0] ReshapeTranspose_IH,
    output [TRANSPOSE_IW_WIDTH-1:0] ReshapeTranspose_IW,
    output [TRANSPOSE_IC_WIDTH-1:0] ReshapeTranspose_IC,
    `endif //TRANSPOSE
    
    `ifdef CONCAT
    // Concat Operator
    output [OP_CODE_WIDTH - 1 : 0] opcode_CONCAT,
    output [CONCAT_InNum_WIDTH -1 : 0] CONCAT_InNum,
    output [CONCAT_Image1StartAddress_WIDTH -1 : 0] CONCAT_StartAdd_1,
    output [CONCAT_Image2StartAddress_WIDTH -1 : 0] CONCAT_StartAdd_2,
    output [CONCAT_Image3StartAddress_WIDTH -1 : 0] CONCAT_StartAdd_3,
    output [CONCAT_Image4StartAddress_WIDTH -1 : 0] CONCAT_StartAdd_4,
    output [CONCAT_IH1_WIDTH -1 : 0] CONCAT_IH_1,
    output [CONCAT_IH2_WIDTH -1 : 0] CONCAT_IH_2,
    output [CONCAT_IH3_WIDTH -1 : 0] CONCAT_IH_3,
    output [CONCAT_IH4_WIDTH -1 : 0] CONCAT_IH_4,
    output [CONCAT_KN1_WIDTH -1 : 0] CONCAT_KN_1,
    output [CONCAT_KN2_WIDTH -1 : 0] CONCAT_KN_2,
    output [CONCAT_KN3_WIDTH -1 : 0] CONCAT_KN_3,
    output [CONCAT_KN4_WIDTH -1 : 0] CONCAT_KN_4,
    `endif
    output [OutputBlock_FlatController_WIDTH-1:0]OutputBlock_FlatController
);

    `include "../common/instructions.vh"
//localparam APPEND = ((1<<OP_CODE_WIDTH) - NO_OF_OPERATOR);
wire [(OUTPUT_WIDTH)-1 : 0] dout_top_master; 
wire [(1<<OP_CODE_WIDTH)-1 : 0] select_line; 
wire wr;
wire done_top_master;
wire [NO_OF_OPERATOR - 1 : 0] ready;

top_master  #(.OP_CODE_WIDTH(OP_CODE_WIDTH), 
 .CNT(CNT),
 .INPUT_WIDTH(INPUT_WIDTH),
 .OUTPUT_WIDTH(OUTPUT_WIDTH),
 .NO_OF_OPERATOR(NO_OF_OPERATOR)) 
top_master(
    .din(din),
    .start(start),
    .clk(clk),
    .op_code(opcode),
    .ready_in(ready),
    .dout(dout_top_master),
    .sel(select_line),
    .write(wr),
    .done(done_top_master)
);

OP_CONV #(.OP_CODE_WIDTH(OP_CODE_WIDTH), 
.CNT(CNT),
.INPUT_WIDTH(OUTPUT_WIDTH),
.OUTPUT_WIDTH(INPUT_WIDTH),
.IW_WIDTH(IW_WIDTH),
.IH_WIDTH(IH_WIDTH),
.IC_WIDTH(IC_WIDTH),
.KN_WIDTH(KN_WIDTH),
.KW_WIDTH(KW_WIDTH),
.KH_WIDTH(KH_WIDTH),
.STRIDE_WIDTH(STRIDE_WIDTH),
.PAD_LEFT_WIDTH(PAD_LEFT_WIDTH),
.PAD_RIGHT_WIDTH(PAD_RIGHT_WIDTH),
.PAD_TOP_WIDTH(PAD_TOP_WIDTH),
.PAD_BOTTOM_WIDTH(PAD_BOTTOM_WIDTH),
.CONV_StartRowSkip_WIDTH(CONV_StartRowSkip_WIDTH),
.CONV_EndRowSkip_WIDTH(CONV_EndRowSkip_WIDTH),
.ADDRESS_WIDTH(ADDRESS_WIDTH),
.CONV_Im2colPrefetch_WIDTH(CONV_Im2colPrefetch_WIDTH),
.CONV_CHANNELDUPLICATE_WIDTH(CONV_CHANNELDUPLICATE_WIDTH)
)
OP_CONV(
    .din(dout_top_master),
    .sel(select_line[`OP_CONV]),
    .write(wr),
    .done(done_top_master),
    .clk(clk),
    .opcode(opcode_conv),
    .IW(IW),
    .IH(IH),
    .IC(IC),
    .KN(KN),
    .KW(KW),
    .KH(KH),
    .KC(KC),
    .conv_type(conv_type),
    .Stride(Stride),
    .Pad_left(Pad_left),
    .Pad_right(Pad_right),
    .Pad_top(Pad_top),
    .Pad_bottom(Pad_bottom),
    .start_row_skip(start_row_skip),
    .end_row_skip(end_row_skip),
    .CONV_Im2colPrefetch(CONV_Im2colPrefetch),
    .CONV_ChannelDuplicate(CONV_ChannelDuplicate),
    .ImageStartAddress(ImageStartAddress_conv),
    .ImageEndAddress(ImageEndAddress_conv),
    .WeightStartAddress(WeightStartAddress_conv),
    .WeightEndAddress(WeightEndAddress_conv),
    .valid(valid[`OP_CONV]),
    .ready(ready[`OP_CONV])
);

`ifdef FC
OP_FC #(.OP_CODE_WIDTH(OP_CODE_WIDTH), 
.CNT(CNT),
.INPUT_WIDTH(OUTPUT_WIDTH),
.OUTPUT_WIDTH(INPUT_WIDTH),
.ADDRESS_WIDTH(ADDRESS_WIDTH),
.WEIGHTROWS_WIDTH(WEIGHTCOLS_WIDTH),
.WEIGHTCOLS_WIDTH(WEIGHTCOLS_WIDTH),
.INPUTROWS_WIDTH(INPUTROWS_WIDTH),
.DROPOUTCONSTANT_WIDTH(DROPOUTCONSTANT_WIDTH),
.FLATTEN_WIDTH(FLATTEN_WIDTH),
.IMAGEDIN_WIDTH(IMAGEDIN_WIDTH),
.FC_VEC2MATCOL_WIDTH(FC_VEC2MATCOL_WIDTH)) 
OP_FC(
    .din(dout_top_master),
    .sel(select_line[`OP_FC]),
    .write(wr),
    .done(done_top_master),
    .clk(clk),
    .valid(valid[`OP_FC]),
    .ready(ready[`OP_FC]),
    .opcode(opcode_FC),
    .weightrows(weightrows),
    .weightcols(weightcols),
    .inputrows(inputrows),
    .dropoutconstant(dropoutconstant),
    .flatten(flatten),
    .imagedim(imagedim_FC),
    .ImageStartAddress(ImageStartAddress_FC),
    .ImageEndAddr(ImageEndAddr_FC),
    .WeightStartAddress(WeightStartAddress_FC),
    .WeightEndAddress(WeightEndAddress_FC),
    .FC_Vec2MatCols(FC_Vec2MatCols)
);
`endif //FC

OP_Outputblock #(.OP_CODE_WIDTH(OP_CODE_WIDTH), 
.CNT(CNT),
.INPUT_WIDTH(OUTPUT_WIDTH),
.OUTPUT_WIDTH(INPUT_WIDTH),
.ADDRESS_WIDTH(ADDRESS_WIDTH),
.CHANNELITR_WIDTH(CHANNELITR_WIDTH),
.KERNELITR_WIDTH(KERNELITR_WIDTH),
.IMAGEDIMOUTPUT_WIDTH(IMAGEDIMOUTPUT_WIDTH),
.IMAGEDIMACC_WIDTH(IMAGEDIMACC_WIDTH),
.ACCEN_WIDTH(ACCEN_WIDTH),
.DISPATCH_ID_WIDTH(DISPATCH_ID_WIDTH),
.DISPATCHEN_WIDTH(DISPATCHEN_WIDTH),
.ACC_ONCHIP_WIDTH(ACC_ONCHIP_WIDTH),
.OH_WIDTH(OH_WIDTH),
.OW_WIDTH(OW_WIDTH),
.OutputBlock_FlatController_WIDTH(OutputBlock_FlatController_WIDTH),
.OutputBlock_AccumulantReadFirst_WIDTH(OutputBlock_AccumulantReadFirst_WIDTH))
OP_Outputblock(
    .din(dout_top_master),
    .sel(select_line[`OP_OutputBlock]),
    .write(wr),
    .done(done_top_master),
    .clk(clk),
    .valid(valid[`OP_OutputBlock]),
    .ready(ready[`OP_OutputBlock]),
    .opcode(opcode_OB),
    .accumulantaddr(accumulantaddr),
    .outputaddr(outputaddr),
    .channelItr(channelItr),
    .kernelItr(kernelItr),
    .ImageDimOutput(ImageDimOutput),
    .ImageDimAcc(ImageDimAcc),
    .AccEn(AccEn),
    .DispatchId(DispatchId),
    .DispatchEn(DispatchEn),
    .Acc_onchip(Acc_onchip),
    .OB_OH(OB_OH),
    .OB_OW(OB_OW),
    .OB_OpWidth(OB_OpWidth),
    .OutputBlock_FlatController(OutputBlock_FlatController),
    .OutputBlock_AccumulantReadFirst(OutputBlock_AccumulantReadFirst)
);

OP_Tailblock #(.OP_CODE_WIDTH(OP_CODE_WIDTH), 
.CNT(CNT),
.INPUT_WIDTH(OUTPUT_WIDTH),
.OUTPUT_WIDTH(INPUT_WIDTH),
.ADDRESS_WIDTH(ADDRESS_WIDTH),
.ACTEN_WIDTH(ACTEN_WIDTH),
.ACTTYPE_WIDTH(ACTTYPE_WIDTH),
.ACTPARAM_WIDTH(ACTPARAM_WIDTH),
.LR_NEG_ALPHA_WIDTH(LR_NEG_ALPHA_WIDTH),
.LR_POS_ALPHA_WIDTH(LR_POS_ALPHA_WIDTH),
.QUANTEN_WIDTH(QUANTEN_WIDTH),
.QUANTSCALE_WIDTH(QUANTSCALE_WIDTH),
.QUANTSHIFT_WIDTH(QUANTSHIFT_WIDTH),

`ifdef GLOBAL_POOL
.GBL_POOL_SCALE_WIDTH(GBL_POOL_SCALE_WIDTH),
.GBL_POOL_SHIFT_WIDTH(GBL_POOL_SHIFT_WIDTH),
.GBL_POOL_EN_WIDTH(GBL_POOL_EN_WIDTH),
`endif

`ifdef POOL 
.POOLEN_WIDTH(POOLEN_WIDTH),
.POOLTYPE_WIDTH(POOLTYPE_WIDTH),
.POOLWIDTH_WIDTH(POOLWIDTH_WIDTH),
.POOLHEIGHT_WIDTH(POOLHEIGHT_WIDTH),
.POOLSTRIDE_WIDTH(POOLSTRIDE_WIDTH),
.POOLPAD_WIDTH(POOLPAD_WIDTH),
.POOLCEIL_WIDTH(POOLCEIL_WIDTH),
.POOLMODCOUNT_WIDTH(POOLMODCOUNT_WIDTH),
.POOLPADSIDES_WIDTH(POOLPADSIDES_WIDTH),
.POOLSCALE_WIDTH(POOLSCALE_WIDTH),
.POOLSHIFT_WIDTH(POOLSHIFT_WIDTH),
`endif

.BIASEN_WIDTH(BIASEN_WIDTH),
.BNCHANNELS_WIDTH(BNCHANNELS_WIDTH),
.BiasWidth_WIDTH(BiasWidth_WIDTH)) 
OP_Tailblock(
    .din(dout_top_master),
    .sel(select_line[`OP_TailBlock]),
    .write(wr),
    .done(done_top_master),
    .clk(clk),
    .ready(ready[`OP_TailBlock]),
    .valid(valid[`OP_TailBlock]),
    .opcode(opcode_TB),
    .ActEn(ActEn),
    .acttype(acttype),
    .ActParam(ActParam),
    .NegAlpha(LR_NegAlpha),
    .PosAlpha(LR_PosAlpha),
    .QuantEn(QuantEn),
    .quantscale(quantscale),
    .quantshift(quantshift),

    `ifdef GLOBAL_POOL
    .gbl_pool_scale(gbl_pool_scale),
    .gbl_pool_shift(gbl_pool_shift),
    .gbl_pool_en(gbl_pool_en),
    `endif

    `ifdef POOL
    .PoolEn(PoolEn),
    .pooltype(pooltype),
    .poolwidth(poolwidth),
    .poolheight(poolheight),
    .poolstride(poolstride),
    .poolpadding(poolpadding),
    .poolceil(poolceil),
    .poolModCount(poolModCount),
    .poolpadsides(poolpadsides),
    .poolscale(poolscale),
    .poolshift(poolshift),
    `endif

    .BiasEn(BiasEn),
    .BiasWidth(BiasWidth),
    .BiasStartAddress(BiasStartAddress),
    .BiasEndAddress(BiasEndAddress)
);

`ifdef MEGA_POOL
OP_POOL#(
.OP_CODE_WIDTH(OP_CODE_WIDTH), 
.CNT(CNT),
.INPUT_WIDTH(OUTPUT_WIDTH),
.OUTPUT_WIDTH(INPUT_WIDTH),
.ADDRESS_WIDTH(ADDRESS_WIDTH),

.POOL_IW_WIDTH(POOL_IW_WIDTH),
.POOL_IH_WIDTH(POOL_IH_WIDTH),
.POOL_IC_WIDTH(POOL_IC_WIDTH),
.POOL_IMG_STA_ADD_WIDTH(POOL_IMG_STA_ADD_WIDTH),
.POOL_IMG_END_ADD_WIDTH(POOL_IMG_END_ADD_WIDTH),
.POOLTYPE_WIDTH(POOLTYPE_WIDTH),
.POOLSCALE_WIDTH(POOLSCALE_WIDTH),
.POOLSHIFT_WIDTH(POOLSHIFT_WIDTH),
.POOLWIDTH_WIDTH(POOLWIDTH_WIDTH),
.POOLHEIGHT_WIDTH(POOLHEIGHT_WIDTH),
.POOLSTRIDE_W_WIDTH(POOLSTRIDE_W_WIDTH),
.POOLSTRIDE_H_WIDTH(POOLSTRIDE_H_WIDTH),
.POOLCEIL_WIDTH(POOLCEIL_WIDTH),
.POOLPAD_L_WIDTH(POOLPAD_L_WIDTH),
.POOLPAD_R_WIDTH(POOLPAD_R_WIDTH),
.POOLPAD_T_WIDTH(POOLPAD_T_WIDTH),
.POOLPAD_B_WIDTH(POOLPAD_B_WIDTH),
.POOL_PREFETCH_WIDTH(POOL_PREFETCH_WIDTH))
OP_POOL(
    .din(dout_top_master),
    .sel(select_line[`OP_POOL]),
    .write(wr),
    .done(done_top_master),
    .clk(clk),
    .ready(ready[`OP_POOL]),
    .valid(valid[`OP_POOL]),
    .opcode(opcode_pool),
    .pool_iw(pool_iw),
    .pool_ih(pool_ih),
    .pool_ic(pool_ic),
    .pool_img_sta_add(pool_img_sta_add),
    .pool_img_end_add(pool_img_end_add),
    .pooltype(pooltype),
    .poolscale(poolscale),
    .poolshift(poolshift),
    .poolwidth(poolwidth),
    .poolheight(poolheight),
    .poolstride_w(poolstride_w),
    .poolstride_h(poolstride_h),
    .poolceil(poolceil),
    .pool_pad_l(pool_pad_l),
    .pool_pad_r(pool_pad_r),
    .pool_pad_t(pool_pad_t),
    .pool_pad_b(pool_pad_b),
    .pool_prefetch(pool_prefetch)
);
`endif

OP_EltWise #(.OP_CODE_WIDTH(OP_CODE_WIDTH),
.CNT(CNT),
.INPUT_WIDTH(OUTPUT_WIDTH),
.OUTPUT_WIDTH(INPUT_WIDTH),
.ADDRESS_WIDTH(ADDRESS_WIDTH),
.ELTWISE_TYPE_WIDTH(ELTWISE_TYPE_WIDTH),
.ELTWISE_SCALE_WIDTH(ELTWISE_SCALE_WIDTH),
.ELTWISE_ZEROPOINT_WIDTH(ELTWISE_ZEROPOINT_WIDTH),
.IH_WIDTH(IH_WIDTH),
.IW_WIDTH(IW_WIDTH),
.IC_WIDTH(IC_WIDTH))
OP_EltWise(
    .din(dout_top_master),
    .sel(select_line[`OP_EltWise]),
    .write(wr),
    .done(done_top_master),
    .clk(clk),
    .opcode(opcode_EltWise),
    .EltWise_type(EltWise_type),
    .LeftOperand_Scale(LeftOperand_Scale),
    .RightOperand_Scale(RightOperand_Scale),
    .LeftOperand_zero_point(LeftOperand_zero_point),
    .RightOperand_zero_point(RightOperand_zero_point),
    .EltWise_IW(EltWise_IW),
    .EltWise_IH(EltWise_IH),
    .EltWise_IC(EltWise_IC),
    .LeftOperand_StartAddress(LeftOperand_StartAddress),
    .RightOperand_StartAddress(RightOperand_StartAddress),
    .LeftOperand_EndAddress(LeftOperand_EndAddress),
    .RightOperand_EndAddress(RightOperand_EndAddress),
    .valid(valid[`OP_EltWise]),
    .ready(ready[`OP_EltWise])
    );

OP_Resize #(
.OP_CODE_WIDTH(OP_CODE_WIDTH),
.CNT(CNT),
.INPUT_WIDTH(OUTPUT_WIDTH),
.OUTPUT_WIDTH(INPUT_WIDTH),
.ADDRESS_WIDTH(ADDRESS_WIDTH),

.RESIZE_IW_WIDTH(RESIZE_IW_WIDTH),
.RESIZE_IH_WIDTH(RESIZE_IH_WIDTH),
.RESIZE_IC_WIDTH(RESIZE_IC_WIDTH),
.RESIZE_IMG_STA_ADD_WIDTH(RESIZE_IMG_STA_ADD_WIDTH),
.RESIZE_IMG_END_ADD_WIDTH(RESIZE_IMG_END_ADD_WIDTH))
OP_RESIZE(
    .din(dout_top_master),
    .sel(select_line[`OP_RESIZE]),
    .write(wr),
    .done(done_top_master),
    .clk(clk),
    .opcode(opcode_resize),
    .resize_iw(resize_iw),
    .resize_ih(resize_ih),
    .resize_ic(resize_ic),
    .resize_img_sta_add(resize_img_sta_add),
    .resize_img_end_add(resize_img_end_add),
    .valid(valid[`OP_RESIZE]),
    .ready(ready[`OP_RESIZE])
);
    

`ifdef TRANSPOSE
OP_ReshapeTranspose # (
    .OP_CODE_WIDTH(OP_CODE_WIDTH),
    .CNT(CNT),
    .INPUT_WIDTH(OUTPUT_WIDTH),
    .OUTPUT_WIDTH(INPUT_WIDTH),
    .ADDRESS_WIDTH(ADDRESS_WIDTH),
    .IW_WIDTH(TRANSPOSE_IW_WIDTH),
    .IH_WIDTH(TRANSPOSE_IH_WIDTH),
    .IC_WIDTH(TRANSPOSE_IC_WIDTH)
  )
  OP_ReshapeTranspose_inst (
    .din(dout_top_master),
    .sel(select_line[`OP_TRANSPOSE]),
    .write(wr),
    .done(done_top_master),
    .clk(clk),
    .opcode(rt_opcode),
    .ReshapeTranspose_IW(ReshapeTranspose_IW),
    .ReshapeTranspose_IH(ReshapeTranspose_IH),
    .ReshapeTranspose_IC(ReshapeTranspose_IC),
    .ReshapeTranspose_StartAddress(ReshapeTranspose_start_address),
    .valid(valid[`OP_TRANSPOSE]),
    .ready(ready[`OP_TRANSPOSE])
  );
`endif //TRANSPOSE
//assign ready = ({APPEND{1'b0}}, ready_TB, ready_OB, ready_FC, ready_conv);
  `ifdef CONCAT
  OP_Concat #(
        .OP_CODE_WIDTH(OP_CODE_WIDTH), 
        .CNT(CNT),
        .OUTPUT_WIDTH(INPUT_WIDTH),
        .INPUT_WIDTH(OUTPUT_WIDTH),
        .CONCAT_Image1StartAddress_WIDTH(CONCAT_Image1StartAddress_WIDTH),
        .CONCAT_Image2StartAddress_WIDTH(CONCAT_Image2StartAddress_WIDTH),
        .CONCAT_Image3StartAddress_WIDTH(CONCAT_Image3StartAddress_WIDTH),
        .CONCAT_Image4StartAddress_WIDTH(CONCAT_Image4StartAddress_WIDTH),
        .CONCAT_IH1_WIDTH(CONCAT_IH1_WIDTH),
        .CONCAT_IH2_WIDTH(CONCAT_IH2_WIDTH),
        .CONCAT_IH3_WIDTH(CONCAT_IH3_WIDTH),
        .CONCAT_IH4_WIDTH(CONCAT_IH4_WIDTH),
        .CONCAT_KN1_WIDTH(CONCAT_KN1_WIDTH),
        .CONCAT_KN2_WIDTH(CONCAT_KN2_WIDTH),
        .CONCAT_KN3_WIDTH(CONCAT_KN3_WIDTH),
        .CONCAT_KN4_WIDTH(CONCAT_KN4_WIDTH),
        .CONCAT_InNum_WIDTH(CONCAT_InNum_WIDTH)

        )
        OP_CONCAT(
        .din(dout_top_master),
        .sel(select_line[`OP_CONCAT]),
        .write(wr),
        .done(done_top_master),
        .clk(clk),
        .opcode(opcode_CONCAT),
        .CONCAT_InNum(CONCAT_InNum),
        .CONCAT_StartAdd_1(CONCAT_StartAdd_1),
        .CONCAT_StartAdd_2(CONCAT_StartAdd_2),
        .CONCAT_StartAdd_3(CONCAT_StartAdd_3),
        .CONCAT_StartAdd_4(CONCAT_StartAdd_4),
        .CONCAT_IH_1(CONCAT_IH_1),
        .CONCAT_IH_2(CONCAT_IH_2),
        .CONCAT_IH_3(CONCAT_IH_3),
        .CONCAT_IH_4(CONCAT_IH_4),
        .CONCAT_KN_1(CONCAT_KN_1),
        .CONCAT_KN_2(CONCAT_KN_2),
        .CONCAT_KN_3(CONCAT_KN_3),
        .CONCAT_KN_4(CONCAT_KN_4),
        .valid(valid[`OP_CONCAT]),
        .ready(ready[`OP_CONCAT])
        );
    `endif
    //assign ready = ({APPEND{1'b0}}, ready_TB, ready_OB, ready_FC, ready_conv);

endmodule
