module top_master_slave_integrate #(parameter OP_CODE_WIDTH = 4, 
            parameter CNT = (INPUT_WIDTH/OUTPUT_WIDTH),
            parameter INPUT_WIDTH = 256,
            parameter OUTPUT_WIDTH = 8) (
                input [(INPUT_WIDTH)-1 : 0] din,
                input start,
                input clk,
                input [(OP_CODE_WIDTH)-1 : 0] opcode,
                output [(OP_CODE_WIDTH)-1 : 0] valid,
                output [3:0] opcode_conv,
                output [9:0] IW = 0,
                output [9:0] IH = 0,
                output [9:0] OW = 0,
                output [9:0] OH = 0,
                output [9:0] IC = 0,
                output [9:0] KN = 0,
                output [13:0] KW = 0,
                output [3:0] KH = 0,
                output [3:0] Stride = 0,
                output [2:0] Pad = 0,
                output [11:0] channelItr,
                output [11:0] kernelItr,
                output [31:0] ImageStartAddress_conv,
                output [31:0] ImageEndAddress_conv,
                output [31:0] WeightStartAddress_conv,
                output [31:0] WeightEndAddress_conv,
                output [3:0] opcode_FC,
                output [15:0] weightrows,
                output [15:0] weightcols,
                output [15:0] inputrows,
                output [7:0] dropoutconstant,
                output [31:0] address,
                output flatten,
                output [19:0] imagedim_FC,
                output [31:0] ImageStartAddress_FC,
                output [31:0] ImageEndAddr_FC,
                output [15:0] KernelIteration,
                output [15:0] RWAddressCountFlatten,
                output [3:0] opcode_OB,
                output [31:0] accumulantaddr,
                output [31:0] outputaddr,
                output [11:0] channelItr_OB,
                output [11:0] kernelItr_OB,
                output [15:0] ImageDimOutput,
                output [15:0] ImageDimAcc,
                output AccEn,
                output [3:0] opcode_TB,
                output BNEn = 0,
                output [9:0] BNchannels = 0,
                output [31:0] BNStartAddress = 0,
                output [31:0] BNEndAddress = 0,
                output ActEn = 0,
                output [3:0] acttype = 0,
                output [7:0] ActParam = 0,
                output QuantEn = 0,
                output [15:0] quantscale = 0,
                output [4:0] quantshift = 0,
                output PoolEn = 0,
                output [2:0] pooltype = 0,
                output [3:0] poolwidth = 0,
                output [3:0] poolheight = 0,
                output [3:0] poolstride = 0,
                output [3:0] poolpadding = 0,
                output BiasEn = 0,
                output FCBiasEn = 0,
                output [31:0] BiasStartAddress = 0,
                output [31:0] BiasEndAddress = 0
    );

wire [(OUTPUT_WIDTH)-1 : 0] dout_top_master; 
wire select_line; 
wire wr;
wire done_top_master;
wire [(OP_CODE_WIDTH)-1 : 0] ready;
wire ready_conv;
wire ready_FC;
wire ready_OB;
wire ready_TB;

top_master top_master(
    .din(din),
    .start(start),
    .clk(clk),
    .op_code(opcode),
    .ready_in(ready),
    .dout(dout_top_master),
    .sel(select_line),
    .write(wr),
    .done(done_top_master)
);

OP_CONV OP_CONV(
    .din(dout_top_master),
    .sel(select_line),
    .write(wr),
    .done(done_top_master),
    .clk(clk),
    .opcode(opcode_conv),
    .IW(IW),
    .IH(IH),
    .OW(OW),
    .OH(OH),
    .IC(IC),
    .KN(KN),
    .KW(KW),
    .KH(KH),
    .Stride(Stride),
    .Pad(Pad),
    .channelItr(channelItr_conv),
    .kernelItr(kernelItr_conv),
    .ImageStartAddress(ImageStartAddress_conv),
    .ImageEndAddress(ImageEndAddress_conv),
    .WeightStartAddress(WeightStartAddress_conv),
    .WeightEndAddress(WeightEndAddress_conv),
    .valid(valid),
    .ready(ready_conv)
);

OP_FC OP_FC(
    .din(dout_top_master),
    .sel(select_line),
    .write(wr),
    .done(done_top_master),
    .clk(clk),
    .valid(valid),
    .ready(ready_Fc),
    .opcode(opcode_FC),
    .weightrows(weightrows),
    .weightcols(weightcols),
    .inputrows(inputrows),
    .dropoutconstant(dropoutconstant),
    .address(address),
    .flatten(flatten),
    .imagedim(imagedim_FC),
    .ImageStartAddress(ImageStartAddress_FC),
    .ImageEndAddr(ImageEndAddr_FC),
    .KernelIteration(KernelIteration),
    .RWAddressCountFlatten(RWAddressCountFlatten)
);

OP_Outputblock OP_Outputblock(
    .din(dout_top_master),
    .sel(select_line),
    .write(wr),
    .done(done_top_master),
    .clk(clk),
    .valid(valid),
    .ready(ready_OB),
    .opcode(opcode_OB),
    .accumulantaddr(accumulantaddr),
    .outputaddr(outputaddr),
    .channelItr(channelItr_OB),
    .kernelItr(kernelItr_OB),
    .ImageDimOutput(ImageDimOutput),
    .ImageDimAcc(ImageDimAcc),
    .AccEn(AccEn)
);

OP_Tailblock OP_Tailblock(
    .din(dout_top_master),
    .sel(select_line),
    .write(wr),
    .done(done_top_master),
    .clk(clk),
    .ready(ready_TB),
    .valid(valid),
    .opcode(opcode_TB),
    .BNEn(BNEn),
    .BNchannels(BNchannels),
    .BNStartAddress(BiasStartAddress),
    .BNEndAddress(BNEndAddress),
    .ActEn(ActEn),
    .acttype(acttype),
    .ActParam(ActParam),
    .QuantEn(QuantEn),
    .quantscale(quantscale),
    .quantshift(quantshift),
    .PoolEn(PoolEn),
    .pooltype(pooltype),
    .poolwidth(poolwidth),
    .poolheight(poolheight),
    .poolstride(poolstride),
    .poolpadding(poolpadding),
    .BiasEn(BiasEn),
    .FCBiasEn(FCBiasEn),
    .BiasStartAddress(BiasStartAddress),
    .BiasEndAddress(BiasEndAddress)
);

assign ready = (ready_conv | ready_FC | ready_OB | ready_TB);

endmodule