module top_master_slave_integrate #(parameter OP_CODE_WIDTH = 4, 
            parameter CNT = (INPUT_WIDTH/OUTPUT_WIDTH),
            parameter INPUT_WIDTH = 256,
            parameter OUTPUT_WIDTH = 8,
            parameter NO_OF_OPERATOR = 4,
            parameter ADDRESS_WIDTH = 32,
            parameter IW_WIDTH = 10,
            parameter IH_WIDTH = 10,
            parameter OW_WIDTH = 10,
            parameter OH_WIDTH = 10,
            parameter IC_WIDTH = 10
            parameter KN_WIDTH = 10,
            parameter KW_WIDTH = 4,
            parameter KH_WIDTH = 4,
            parameter STRIDE_WIDTH = 4,
            parameter PAD_WIDTH = 3,
            parameter CONV_CHANNELITR_WIDTH = 12,
            parameter CONV_KERNELITR_WIDTH = 12,
            parameter WEIGHTROWS_WIDTH = 16,
            parameter WEIGHTCOLS_WIDTH = 16,
            parameter INPUTROWS_WIDTH = 16,
            parameter DROPOUTCONSTANT_WIDTH = 8,
            parameter FLATTEN_WIDTH = 1,
            parameter IMAGEDIN_WIDTH = 20
            parameter KERNELITERATION_WIDTH = 16,
            parameter RWADDRESSCOUNTFLATTEN_WIDTH = 16,
            parameter OB_CHANNELITR_WIDTH = 12,
            parameter OB_KERNELITR_WIDTH = 12,
            parameter IMAGEDIMOUTPUT_WIDTH = 16,
            parameter IMAGEDIMACC_WIDTH = 16,
            parameter ACCEN_WIDTH = 1,
            parameter BNEN_WIDTH = 1,
            parameter ACTEN_WIDTH = 1,
            parameter ACTTYPE_WIDTH = 4,
            parameter ACTPARAM_WIDTN = 8,
            parameter QUANTEN_WIDTH = 1,
            parameter QUANTSCALE_WIDTH = 16,
            parameter QUANTSHIFT_WIDTH = 5,
            parameter POOLEN_WIDTH = 1,
            parameter POOLTYPE_WIDTH = 3,
            parameter POOLWIDTH_WIDTH = 4,
            parameter POOLHEIGHT_WIDTH = 4,
            parameter POOLSTRIDE_WIDTH = 4,
            parameter POOLPADDING_WIDTH = 4,
            parameter BIASEN_WIDTH = 1,
            parameter BNCHANNELS_WIDTH = 10,
            parameter FCBIASEN = 1
            ) 
            (
                input [(INPUT_WIDTH)-1 : 0] din,
                input start,
                input clk,
                input [(OP_CODE_WIDTH)-1 : 0] opcode,
                output [(OP_CODE_WIDTH)-1 : 0] valid,
                output [OP_CODE_WIDTH - 1 : 0] opcode_conv,
                output [IW_WIDTH - 1 : 0] IW,
                output [IH_WIDTH - 1 : 0] IH,
                output [OW_WIDTH - 1 : 0] OW,
                output [OH_WIDTH - 1 : 0] OH,
                output [IC_WIDTH - 1 : 0] IC,
                output [KN_WIDTH - 1 : 0] KN,
                output [KW_WIDTH - 1 : 0] KW,
                output [KH_WIDTH - 1 : 0] KH,
                output [STRIDE_WIDTH - 1 : 0] Stride,
                output [PAD_WIDTH - 1 : 0] Pad,
                output [CONV_CHANNELITR_WIDTH - 1 : 0] channelItr,
                output [CONV_KERNELITR_WIDTH - 1 : 0] kernelItr,
                output [ADDRESS_WIDTH - 1 : 0] ImageStartAddress_conv,
                output [ADDRESS_WIDTH - 1 : 0] ImageEndAddress_conv,
                output [ADDRESS_WIDTH - 1 : 0] WeightStartAddress_conv,
                output [ADDRESS_WIDTH - 1 : 0] WeightEndAddress_conv,
                output [OP_CODE_WIDTH - 1 : 0] opcode_FC,
                output [WEIGHTROWS_WIDTH - 1 : 0] weightrows,
                output [WEIGHTCOLS_WIDTH - 1 : 0] weightcols,
                output [INPUTROWS_WIDTH - 1 : 0] inputrows,
                output [DROPOUTCONSTANT_WIDTH -1 : 0] dropoutconstant,
                output [FLATTEN_WIDTH -1 : 0] flatten,
                output [IMAGEDIN_WIDTH -1 : 0] imagedim_FC,
                output [ADDRESS_WIDTH - 1 : 0] ImageStartAddress_FC,
                output [ADDRESS_WIDTH - 1 : 0] ImageEndAddr_FC,
                output [KERNELITERATION_WIDTH - 1 : 0] KernelIteration,
                output [RWADDRESSCOUNTFLATTEN_WIDTH -1 : 0] RWAddressCountFlatten,
                output [OP_CODE_WIDTH -1 : 0] opcode_OB,
                output [ADDRESS_WIDTH - 1 : 0] accumulantaddr,
                output [ADDRESS_WIDTH - 1 : 0] outputaddr,
                output [OB_CHANNELITR_WIDTH -1 : 0] channelItr_OB,
                output [OB_KERNELITR_WIDTH - 1 : 0] kernelItr_OB,
                output [IMAGEDIMOUTPUT_WIDTH -1 : 0] ImageDimOutput,
                output [IMAGEDIMACC_WIDTH -1 : 0] ImageDimAcc,
                output [ACCEN_WIDTH -1 : 0] AccEn,
                output [OP_CODE_WIDTH - 1 : 0] opcode_TB,
                output [BNEN_WIDTH - 1 : 0] BNEn,
                output [BNCHANNELS_WIDTH -1 : 0] BNchannels,
                output [ADDRESS_WIDTH - 1 : 0] BNStartAddress,
                output [ADDRESS_WIDTH - 1 : 0] BNEndAddress,
                output [ACTEN_WIDTH - 1 : 0] ActEn,
                output [ACTTYPE_WIDTH - 1 : 0] acttype,
                output [ACTPARAM_WIDTN - 1 : 0] ActParam,
                output [QUANTEN_WIDTH - 1 : 0] QuantEn,
                output [QUANTSCALE_WIDTH - 1 : 0] quantscale,
                output [QUANTSHIFT_WIDTH - 1 : 0] quantshift,
                output [POOLEN_WIDTH - 1 : 0] PoolEn,
                output [POOLTYPE_WIDTH - 1 : 0] pooltype,
                output [POOLWIDTH_WIDTH - 1 : 0] poolwidth,
                output [POOLHEIGHT_WIDTH - 1 : 0] poolheight,
                output [POOLSTRIDE_WIDTH - 1 : 0] poolstride,
                output [POOLPADDING_WIDTH - 1 : 0] poolpadding,
                output [BIASEN_WIDTH - 1 : 0] BiasEn,
                output [FCBIASEN - 1 : 0] FCBiasEn,
                output [ADDRESS_WIDTH - 1 : 0] BiasStartAddress,
                output [ADDRESS_WIDTH - 1 : 0] BiasEndAddress
    );

    `include "instructions.vh"
localparam APPEND = ((1<<OP_CODE_WIDTH) - NO_OF_OPERATOR);
wire [(OUTPUT_WIDTH)-1 : 0] dout_top_master; 
wire [(1<<OP_CODE_WIDTH)-1 : 0] select_line; 
wire wr;
wire done_top_master;
wire [(1<<OP_CODE_WIDTH)-1 : 0] ready;
wire ready_conv;
wire ready_FC;
wire ready_OB;
wire ready_TB;

top_master  #(.OP_CODE_WIDTH(OP_CODE_WIDTH), 
 .CNT(CNT),
 .INPUT_WIDTH(INPUT_WIDTH),
 .OUTPUT_WIDTH(OUTPUT_WIDTH)) top_master(
    .din(din),
    .start(start),
    .clk(clk),
    .op_code(opcode),
    .ready_in(ready),
    .dout(dout_top_master),
    .sel(select_line),
    .write(wr),
    .done(done_top_master)
);

OP_CONV #(.OP_CODE_WIDTH(OP_CODE_WIDTH), 
.CNT(CNT),
.INPUT_WIDTH(INPUT_WIDTH),
.OUTPUT_WIDTH(OUTPUT_WIDTH),
.IW_WIDTH(IW_WIDTH),
.IH_WIDTH(IH_WIDTH),
.OW_WIDTH(OW_WIDTH),
.OH_WIDTH(OH_WIDTH),
.IC_WIDTH(IC_WIDTH),
.KN_WIDTH(KN_WIDTH),
.KW_WIDTH(KW_WIDTH),
.KH_WIDTH(KH_WIDTH),
.STRIDE_WIDTH(STRIDE_WIDTH),
.PAD_WIDTH(PAD_WIDTH),
.CHANNELITR_WIDTH(CONV_CHANNELITR_WIDTH),
.KERNELITR_WIDTH(CONV_KERNELITR_WIDTH),
.ADDRESS_WIDTH(ADDRESS_WIDTH))
OP_CONV(
    .din(dout_top_master),
    .sel(select_line[`Opcode]),
    .write(wr),
    .done(done_top_master),
    .clk(clk),
    .opcode(opcode_conv),
    .IW(IW),
    .IH(IH),
    .OW(OW),
    .OH(OH),
    .IC(IC),
    .KN(KN),
    .KW(KW),
    .KH(KH),
    .Stride(Stride),
    .Pad(Pad),
    .channelItr(channelItr_conv),
    .kernelItr(kernelItr_conv),
    .ImageStartAddress(ImageStartAddress_conv),
    .ImageEndAddress(ImageEndAddress_conv),
    .WeightStartAddress(WeightStartAddress_conv),
    .WeightEndAddress(WeightEndAddress_conv),
    .valid(valid[`Opcode]),
    .ready(ready_conv[`Opcode])
);

OP_FC #(.OP_CODE_WIDTH(OP_CODE_WIDTH), 
.CNT = (CNT),
.INPUT_WIDTH(INPUT_WIDTH),
.OUTPUT_WIDTH(OUTPUT_WIDTH),
.ADDRESS_WIDTH(ADDRESS_WIDTH),
.WEIGHTROWS_WIDTH(WEIGHTCOLS_WIDTH),
.WEIGHTCOLS_WIDTH(WEIGHTCOLS_WIDTH),
.INPUTROWS_WIDTH(INPUTROWS_WIDTH),
.DROPOUTCONSTANT_WIDTH(DROPOUTCONSTANT_WIDTH),
.FLATTEN_WIDTH(FLATTEN_WIDTH),
.IMAGEDIN_WIDTH(IMAGEDIN_WIDTH),
.KERNELITERATION_WIDTH(KERNELITERATION_WIDTH),
.RWADDRESSCOUNTFLATTEN_WIDTH(RWADDRESSCOUNTFLATTEN_WIDTH)) 
OP_FC(
    .din(dout_top_master),
    .sel(select_line[`Opcode]),
    .write(wr),
    .done(done_top_master),
    .clk(clk),
    .valid(valid[`Opcode]),
    .ready(ready_Fc[`Opcode]),
    .opcode(opcode_FC),
    .weightrows(weightrows),
    .weightcols(weightcols),
    .inputrows(inputrows),
    .dropoutconstant(dropoutconstant),
    .flatten(flatten),
    .imagedim(imagedim_FC),
    .ImageStartAddress(ImageStartAddress_FC),
    .ImageEndAddr(ImageEndAddr_FC),
    .KernelIteration(KernelIteration),
    .RWAddressCountFlatten(RWAddressCountFlatten)
);

OP_Outputblock #(.OP_CODE_WIDTH(OP_CODE_WIDTH), 
.CNT = (CNT),
.INPUT_WIDTH(INPUT_WIDTH),
.OUTPUT_WIDTH(OUTPUT_WIDTH),
.ADDRESS_WIDTH(ADDRESS_WIDTH),
.CHANNELITR_WIDTH(OB_CHANNELITR_WIDTH),
.KERNELITR_WIDTH(OB_KERNELITR_WIDTH),
.IMAGEDIMOUTPUT_WIDTH(IMAGEDIMOUTPUT_WIDTH),
.IMAGEDIMACC_WIDTH(IMAGEDIMACC_WIDTH),
.ACCEN_WIDTH(ACCEN_WIDTH))
OP_Outputblock(
    .din(dout_top_master),
    .sel(select_line[`Opcode]),
    .write(wr),
    .done(done_top_master),
    .clk(clk),
    .valid(valid[`Opcode]),
    .ready(ready_OB[`Opcode]),
    .opcode(opcode_OB),
    .accumulantaddr(accumulantaddr),
    .outputaddr(outputaddr),
    .channelItr(channelItr_OB),
    .kernelItr(kernelItr_OB),
    .ImageDimOutput(ImageDimOutput),
    .ImageDimAcc(ImageDimAcc),
    .AccEn(AccEn)
);

OP_Tailblock #(.OP_CODE_WIDTH = 4, 
.CNT(CNT),
.INPUT_WIDTH(INPUT_WIDTH),
.OUTPUT_WIDTH (OUTPUT_WIDTH),
.ADDRESS_WIDTH(ADDRESS_WIDTH),
.BNEN_WIDTH(BNEN_WIDTH),
.ACTEN_WIDTH(ACTEN_WIDTH),
.ACTTYPE_WIDTH(ACTTYPE_WIDTH),
.ACTPARAM_WIDTN(ACTPARAM_WIDTN),
.QUANTEN_WIDTH(QUANTEN_WIDTH),
.QUANTSCALE_WIDTH(QUANTSCALE_WIDTH),
.QUANTSHIFT_WIDTH(QUANTSHIFT_WIDTH),
.POOLEN_WIDTH(POOLEN_WIDTH),
.POOLTYPE_WIDTH(POOLTYPE_WIDTH),
.POOLWIDTH_WIDTH(POOLWIDTH_WIDTH),
.POOLHEIGHT_WIDTH(POOLHEIGHT_WIDTH),
.POOLSTRIDE_WIDTH(POOLSTRIDE_WIDTH),
.POOLPADDING_WIDTH(POOLPADDING_WIDTH),
.BIASEN_WIDTH(BIASEN_WIDTH),
.BNCHANNELS_WIDTH(BNCHANNELS_WIDTH),
.FCBIASEN(FCBIASEN)) 
OP_Tailblock(
    .din(dout_top_master),
    .sel(select_line[`Opcode]),
    .write(wr),
    .done(done_top_master),
    .clk(clk),
    .ready(ready_TB[`Opcode]),
    .valid(valid[`Opcode]),
    .opcode(opcode_TB),
    .BNEn(BNEn),
    .BNchannels(BNchannels),
    .BNStartAddress(BiasStartAddress),
    .BNEndAddress(BNEndAddress),
    .ActEn(ActEn),
    .acttype(acttype),
    .ActParam(ActParam),
    .QuantEn(QuantEn),
    .quantscale(quantscale),
    .quantshift(quantshift),
    .PoolEn(PoolEn),
    .pooltype(pooltype),
    .poolwidth(poolwidth),
    .poolheight(poolheight),
    .poolstride(poolstride),
    .poolpadding(poolpadding),
    .BiasEn(BiasEn),
    .FCBiasEn(FCBiasEn),
    .BiasStartAddress(BiasStartAddress),
    .BiasEndAddress(BiasEndAddress)
);

assign ready = ({APPEND{1'b0}}, ready_TB, ready_OB, ready_FC, ready_conv);

endmodule